### ISSUE TITLE
Show a message when command has ended

### ISSUE THREAD

**Issue by jeffrey734** [mug896/bash-stepping-xtrace#2]
Hi, thanks for your work. That's a very interesting tool.

I was wondering if you could add something to show a message when the command has ended it's work.
Like if a command has a long process like apt update or upgrade we can stay waiting while the update is finished.

I tried to add something around line 65, but it doesn't work properly in all circumstances.

I tried to achieve something like that
+:42:sudo apt upgrade -y
....
intallation verbose
....
************ command ended press enter to continue ************

I can share more if needed, but I guess you could understand your way better than me. 

Thanks

**Comment by mug896** [comment]
I have added "DONE" message in the xtrace.sh

**Comment by jeffrey734** [comment]
Good, that's perfect thanks
